# Generated by Django 2.2.5 on 2019-11-21 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RSSG', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='content',
            new_name='content_1',
        ),
        migrations.AddField(
            model_name='about',
            name='content_2',
            field=models.TextField(default=datetime.datetime(2019, 11, 21, 16, 14, 13, 890897, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
