# Generated by Django 2.2.5 on 2019-11-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSG', '0003_gallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='image_array_1',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_array_2',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
