# Generated by Django 2.2.5 on 2019-11-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSG', '0005_auto_20191121_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
