# Generated by Django 2.2.5 on 2019-11-22 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RSSG', '0006_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpha',
            name='email',
            field=models.CharField(default=datetime.datetime(2019, 11, 22, 4, 6, 20, 657526, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alpha',
            name='name',
            field=models.CharField(default=datetime.datetime(2019, 11, 22, 4, 6, 31, 527581, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alpha',
            name='profile_img',
            field=models.ImageField(default=datetime.datetime(2019, 11, 22, 4, 6, 34, 825383, tzinfo=utc), upload_to='alpha_profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alpha',
            name='since',
            field=models.CharField(default=datetime.datetime(2019, 11, 22, 4, 6, 37, 410667, tzinfo=utc), max_length=4),
            preserve_default=False,
        ),
    ]
