# Generated by Django 2.2.5 on 2019-11-22 05:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RSSG', '0007_auto_20191122_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpha',
            name='to',
            field=models.CharField(default=datetime.datetime(2019, 11, 22, 5, 30, 43, 714671, tzinfo=utc), max_length=4),
            preserve_default=False,
        ),
    ]
