# Generated by Django 2.2.5 on 2019-11-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSG', '0009_auto_20191123_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_array_1',
            field=models.ImageField(default='default.jpg', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_array_2',
            field=models.ImageField(default='default.jpg', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_array_3',
            field=models.ImageField(default='default.jpg', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_array_4',
            field=models.ImageField(default='default.jpg', upload_to='gallery'),
        ),
    ]
