# Generated by Django 2.2.5 on 2019-11-24 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RSSG', '0010_auto_20191123_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='explanation',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operations',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='ops'),
        ),
        migrations.AddField(
            model_name='operations',
            name='implementation_year',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operations',
            name='name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operations',
            name='purpose_of_this_op',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
