# Generated by Django 2.2.5 on 2019-11-26 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RSSG', '0011_auto_20191124_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='announcements',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
