# Generated by Django 2.2.5 on 2019-11-26 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RSSG', '0012_home_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
