# Generated by Django 2.2.5 on 2019-12-01 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RSSG', '0013_home_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='vid',
            field=models.FileField(default=django.utils.timezone.now, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
