# Generated by Django 2.2.5 on 2019-12-01 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RSSG', '0014_gallery_vid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='vid',
            new_name='vid_1',
        ),
        migrations.AddField(
            model_name='gallery',
            name='vid_2',
            field=models.FileField(default=django.utils.timezone.now, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='vid_3',
            field=models.FileField(default=django.utils.timezone.now, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='vid_4',
            field=models.FileField(default=django.utils.timezone.now, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
