# Generated by Django 2.2.5 on 2019-12-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSSG', '0015_auto_20191201_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='vid_1',
            new_name='vid',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image_array_4',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='vid_2',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='vid_3',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='vid_4',
        ),
    ]
